on:
  push:
    branches:
      - cicd

name: CI

jobs:
  build_and_test:
    name: Build and test charger-node
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install system dependencies
        run: sudo apt-get install -y clang
      - name: Install Rust nightly toolchain and wasm32 target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
      - name: Install Rust nightly toolchain and aarch64 target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          override: true
      #- name: Run unit tests
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #- name: Build Linux x86_64 release
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: build
      #    args: --release
      - name: Build Linux aarch64 release
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
      - run: ls -altr target/
      - run: ls -altr target/release
      #- name: Upload x86_64 binary
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: charger-node_x86_64-linux
      #    path: target/
      #- name: Upload aarch64 binary
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: charger-node_aarch64-linux
      #    path: target/